### PR TITLE
Fix the `inline_python_run` command

### PR DESCRIPTION
**Pull request by rahul-ramadas**
The `inline_python_run` command was not working. This fixes it, and some other miscellaneous things.

### CODE REVIEW

**Comment by apiad** [comment]
Thanks, looks great!

**Comment by rahul-ramadas** [comment]
Do mind creating a new release so that it gets picked up by Package Control?

**Comment by apiad** [comment]
Done!

**Comment by rahul-ramadas** [comment]
I don't think Package Control will like the version you have used; the `v` prefix to be precise. You will have to change it to conform exactly to [Semantic Versioning](http://semver.org/).

**Comment by apiad** [comment]
Yes, I see. Should be fixed now. Thanks again!

**Pull request merged**
